app:
    resource: '@AppBundle/Controller/'
    type: annotation

# fos_user_security:
    # resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    
# fos_user_group:
    # resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    # prefix: /group

# fos_user_profile:
    # resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    # prefix: /profile

# fos_user_register:
    # resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    # prefix: /register

# fos_user_resetting:
    # resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    # prefix: /resetting

# fos_user_change_password:
    # resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    # prefix: /profile   

# sonata_user_security:
    # resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

# sonata_user_resetting:
    # resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    # prefix: /resetting

# sonata_user_profile:
    # resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    # prefix: /profile

# sonata_user_register:
    # resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    # prefix: /register

# sonata_user_change_password:
    # resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    # prefix: /profile

# sonata_user_admin_security:
    # resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    # prefix: /admin

# sonata_user_admin_resetting:
    # resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    # prefix: /admin/resetting     

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin/login
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
# easy_admin_bundle:
    # resource: "@EasyAdminBundle/Controller/"
    # type:     annotation
    # prefix:   /backoffice