
services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app_group_registration:
        class: AppBundle\Form\GroupType
        tags:
            - { name: form.type, alias: app_group_registration }
        
    app.form.change_password:
        class: FOS\UserBundle\Form\Type\ChangePasswordFormType
        tags:
            - { name: form.type, alias: fos_user_change_password }
            
    app.admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }
    
    # app.form.handler.registration:
        # class: AppBundle\Form\Handler\RegistrationFormHandler
        # arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
        # scope: request
        # public: false
